uploads = []

[[generated]]
id = "VlstVNtTX5XD8oJLvFpIa"
uri = "file://artifacts/oplexa/assets/images/icon.png"
type = "image"
title = "oplexa-ai-icon"

[[outputs]]
id = "NMZDrhIp71zJdhN0Yiv-f"
uri = "file://dr-nisha-production.tar.gz"
type = "unspecified"
title = "Dr. Nisha — Production Ready Package"

[[outputs]]
id = "Ee-UBlK-VOT4OjDcD64Vh"
uri = "file://dr-nisha-nextjs.tar.gz"
type = "unspecified"
title = "Dr. Nisha — Next.js Fixed (v15.2.4)"
